#!/bin/bash

function checkspace {
	CURRENT=$(df $1 | grep $1 | awk '{ print $5}' | sed 's/%//g')
	THRESHOLD=90
	HOSTNAME=`hostname`

	if [ "$CURRENT" -gt "$THRESHOLD" ] ; then
    		mail -s "$HOSTNAME: Disk Space Alert on $1" admin@inspirehep.net <<EOF
Your $1 partition on $HOSTNAME is critically low. Used: $CURRENT%
EOF
	fi
}

checkspace /opt
checkspace /tmp

exit 0
